"""Add tokens column

Revision ID: 07db46f8cfd5
Revises: 40ea99210383
Create Date: 2025-03-03 08:07:44.314355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07db46f8cfd5'
down_revision: Union[str, None] = '40ea99210383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokens')
    # ### end Alembic commands ###
