"""Add is_ready column to Quiz

Revision ID: 40ea99210383
Revises: acb58f769655
Create Date: 2025-03-01 21:29:55.828328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ea99210383'
down_revision: Union[str, None] = 'acb58f769655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('is_ready', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'is_ready')
    # ### end Alembic commands ###
