"""Added ON DELETE CASCADE to document-quiz relation

Revision ID: 5c780912185d
Revises: 7738fe8e7a2e
Create Date: 2025-03-06 18:28:30.348207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c780912185d'
down_revision: Union[str, None] = '7738fe8e7a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_quiz_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quiz_results_quiz_id_fkey', 'quiz_results', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_results', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('quizzes_document_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_document_id_fkey', 'quizzes', 'documents', ['document_id'], ['id'])
    op.drop_constraint(None, 'quiz_results', type_='foreignkey')
    op.create_foreign_key('quiz_results_quiz_id_fkey', 'quiz_results', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quiz_id_fkey', 'questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_id_fkey', 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
