"""Add isedit column

Revision ID: 7738fe8e7a2e
Revises: 07db46f8cfd5
Create Date: 2025-03-03 08:23:54.296169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7738fe8e7a2e'
down_revision: Union[str, None] = '07db46f8cfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_edit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_edit')
    # ### end Alembic commands ###
